#ifndef TPLASTICITYREFACET_H__
#define TPLASTICITYREFACET_H__

enum
{
    PLASTICITYREFACET_TOPOLOGY         = 1000,
        PLASTICITYREFACET_TOPOLOGY_TRIS    = 0,
        PLASTICITYREFACET_TOPOLOGY_NGONS   = 1,

    PLASTICITYREFACET_OPTIONS_MODE     = 1001,
        PLASTICITYREFACET_OPTIONS_SIMPLE   = 0,
        PLASTICITYREFACET_OPTIONS_ADVANCED = 1,

    PLASTICITYREFACET_TOLERANCE        = 1010,
    PLASTICITYREFACET_ANGLE            = 1011,

    PLASTICITYREFACET_MIN_WIDTH        = 1020,
    PLASTICITYREFACET_MAX_WIDTH        = 1021,
    PLASTICITYREFACET_CURVE_CHORD_TOL  = 1022,
    PLASTICITYREFACET_CURVE_CHORD_ANG  = 1023,
    PLASTICITYREFACET_SURF_PLANE_TOL   = 1024,
    PLASTICITYREFACET_SURF_ANGLE_TOL   = 1025,

    PLASTICITYREFACET_GRP_SIMPLE       = 2000,
    PLASTICITYREFACET_GRP_ADVANCED     = 2001
};

#endif // TPLASTICITYREFACET_H__
